//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int MatchID { get; set; }
        public int Player1 { get; set; }
        public Nullable<int> Player2 { get; set; }
        public int WordID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int StatusID { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
        public virtual Words Words { get; set; }
    }
}
