//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchScores
    {
        public int PlayerID { get; set; }
        public int MatchID { get; set; }
        public int ResultID { get; set; }
        public int Points { get; set; }
    
        public virtual Matches Matches { get; set; }
        public virtual MatchResults MatchResults { get; set; }
        public virtual Players Players { get; set; }
    }
}
